### ISSUE TITLE
Disable ligatures in fixed-width text

### ISSUE THREAD

**Issue by jbednar** [pyviz/nbsite#120]
Ligatures make text more readable in paragraphs, but for fixed-width text like source code they interfere with character spacing. E.g. in the original text, these three items were lined up by the equation symbol, but when rendered as HTML using sphinx and nbsite, come out with ligature-related space differences from the "fi" in "fields":

![image](https://user-images.githubusercontent.com/1695496/57408472-5ae7d580-71ab-11e9-919b-35d5d09224e6.png)

I can't find anything in the [sphinx documentation about ligatures](https://www.sphinx-doc.org/en/master/search.html?q=ligatures), but http://www.mos6581.org/rinohtype/sphinx_stylesheet.html mentions them, so maybe there is some way to turn them off, preferably just for fixed-with fonts like code listings (but if not, for all text).

**Comment by jbednar** [comment]
The JS console inspect feature indicates something about "liga" being in the "font-feature-settings", if that's any help:

![image](https://user-images.githubusercontent.com/1695496/57408792-393b1e00-71ac-11e9-8bd2-0c44ad864d4d.png)

**Comment by jsignell** [comment]
As a css issue, this actually belongs on the sphinx theme.

**Comment by jbednar** [comment]
Sure.
