### ISSUE TITLE
Regenerate CNAME file

### ISSUE THREAD

**Issue by jlstevens** [pyviz/nbsite#41]
Github requires a CNAME file on the gh-pages to set up custom domains e.g for [pyviz](https://github.com/pyviz/pyviz/tree/gh-pages). If this file is clobbered, DNS breaks and you get a 404 error.

The simplest fix would probably be to declare the domain (e.g pyviz.org) and have the option to generate the CNAME file for each website build (the file is very simple). This option should probably be requested explicitly as always adding a CNAME file will probably have unintended consequences.

**Comment by ceball** [comment]
Alternative suggestion to consider from Philipp, taken from a conversation elsewhere: "just ensure that the CNAME isn't added in the latest commit".

**Comment by ceball** [comment]
Note: github auto commits CNAME to the docs branch when you define a custom domain in the repo settings page. 

It's possible other such things might happen (i.e. where making a change to project settings via the github website results in modifications to the docs branch).

**Comment by jlstevens** [comment]
> It's possible other such things might happen (i.e. where making a change to project settings via the github website results in modifications to the docs branch).

I don't think there are too many such things to worry about. I know github supports jekyll themes and things but you won't be using that if you are using nbsite. CNAME is definitely the most important such modification that Github settings might apply that I know about.

**Comment by ceball** [comment]
Already supported by the travis/gh pages integration, but need to document.

**Comment by jsignell** [comment]
Just to capture this here, if you include fqdn in the travis deploy section then the settings tab on GH will autopopulate with the CNAME. No need to add it manually.
