### ISSUE TITLE
Theming

### ISSUE THREAD

**Issue by ceball** [pyviz/nbsite#42]
jbednar:

* I think PyViz should have a default basic theme shared across all or nearly all our projects

* Most of our projects should have their own theme, but it should have just a few colors modified from the PyViz default theme to match the dominant colors in the logo.  E.g. I did that for pyviz.org by starting with the green colors in the GeoViews theme and replacing them with the blues and yellows of the PyViz logo.  This worked well, but (a) it was extraordinarily hard to tell which bits of the theme to edit to change that (I had to try replacing all colors, making sure that worked, then bisect to find which one controlled which bit), and (b) it seems like most of our projects can share nearly the same theme apart from these few color changes, and thus it would be nice to share the same file and add just the few overrides needed to distinguish that site from others.

* nbsite's default theme for derived projects should be different from the default theme we use in PyViz; it's good for the PyViz projects to all look similar, but anyone else who builds a site shouldn't end up with a site that looks like PyViz; it can look more generic by default, and should be visually distinct.

* nbsite itself should have a theme similar to the other PyViz tools.

**Comment by jsignell** [comment]
Closed in #121
