### ISSUE TITLE
nbpagebuild script should have option to avoid overriding existing files

### ISSUE THREAD

**Issue by philippjfr** [pyviz/nbsite#43]
The ``nbsite_nbpagebuild.py`` script generates rst files for the notebooks in ``examples``. Sometimes these rst files require some customization which means that an rst file is already checked into the repo, the script simply overwrites the customized rst file, overriding any customizations. At minimum there should be an option to avoid overwriting existing rst files.

**Comment by jlstevens** [comment]
Maybe the script could compare created and modified timestamps? Maybe it could assume that rst files that have a modified timestamp after the creation timestamp were edited by the user? Then issue a warning noting that the file was skipped due to modifications and might need updating?

**Comment by jbednar** [comment]
Seems like it could avoid overwriting existing rst files in all cases, as long as we have a way to clear out generated ones when we need to.

**Comment by jlstevens** [comment]
> ... as we have a way to clear out generated ones when we need to

How would you know which ones were generated versus modified without using something like my timestamp proposal? A single switch to either overwrite or not overwrite all the files doesn't really solve the problem imho as you'll have a mix of 'vanillia' files that need updating and some which have been customized.

**Comment by jbednar** [comment]
A timestamp won't distinguish that, but git status would...
