### ISSUE TITLE
Broken links to download notebooks

### ISSUE THREAD

**Issue by jbednar** [pyviz/nbsite#59]
At least on pyviz.org, the links to download .ipynb files are broken.  E.g. on http://pyviz.org/tutorial/00_Setup.html, the link goes to https://raw.githubusercontent.com/pyviz/notebooks/00_Setup.ipynb , when it should go to https://raw.githubusercontent.com/pyviz/pyviz/master/notebooks/00_Setup.ipynb .

**Comment by ceball** [comment]
Should be fixed in v0.4.4a10 onwards
