### ISSUE TITLE
Remove extra space inserted after links before punctuation

### ISSUE THREAD

**Issue by ceball** [pyviz/nbsite#64]
See e.g. https://github.com/ioam/holoviews/pull/2608#issue-183537510

**Comment by jsignell** [comment]
Just noting that this is not a css problem, but rather a problem with the way html is generated from rst in nbsite (not sure if nbconvert is responsible or not). If you inspect the html you'll see that links end up with the a tags on new lines like:

```html
     <p>
      Colorcet is supported and mantained by
      <a class="reference external" href="https://anaconda.com">
       Anaconda
      </a>
      .
     </p>
```

This new line renders as a space after the link.

**Comment by jbednar** [comment]
I'd really like to see this problem go away; it's very annoying!
